version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the frontend..."
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build # Adjust based on your build output directory
